### ISSUE TITLE
I can have different names!

### ISSUE THREAD

**Issue by pauloancheta** [jzntam/CodeCore_Alumni#8]
With the current state of the models, this is possible:

```
u = User.create(first_name: "Paulo" ...)
Contact.create(first_name: "Some other first name", last_name: "some other last name", ... , user: u)
u.contacts.first.first_name => "some other first name"
```

users would have a different first name as the User model. Different last name and different email address.

**Comment by jzntam** [comment]
yes its a definite issue. How do we take the user info from the sign up or oauth and populate it into the contact table? Each user can only have one contact (which is their profile). I did this in a hacky way, but if there is a better way we should fix it.

**Comment by tylersuzukinelson** [comment]
What is the purpose of having separate User and Contact models?

Tyler Suzuki Nelson

tyler.nelson@alumni.ubc.ca
604-441-5743
tylersuzukinelson.com
